version: "{build}"

clone_depth: 5

environment:
  matrix:
    - platform: "x86"

init:
  # Enable symlinks in git; note that this requires to clone
  # the repo with admin rights, which AppVeyor does by default
  - git config --global core.symlinks true

install:
  - ps: Install-Product node "10" $env:platform
  - npm install

build: off

before_test:
  - curl https://v4.ifconfig.co/

test_script:
  - node -v
  - npm -v
  - npm run ci

matrix:
  fast_finish: true

cache:
  - 'node_modules -> appveyor.yml,package.json,package-lock.json'
