	<div class="endorse">
		<div class="container">
			<div class="row-fluid">
				<div class="span12">
					<h3>Mad Love:</h3>
				</div>
			</div>
		
			<div class="row-fluid" align="center">
              <div>	
			      <div> <blockquote class="twitter-tweet"><p>if you're looking for a CDN to host @<a href="https://twitter.com/twbootstrap">twbootstrap</a>, the folks at @<a href="https://twitter.com/netdnadeveloper">netdnadeveloper</a> have graciously provided a free one <a href="http://t.co/MsH8NBJ1" title="http://www.bootstrapcdn.com/">bootstrapcdn.com</a></p>&mdash; Twitter Open Source (@TwitterOSS) <a href="https://twitter.com/TwitterOSS/status/233235680166293504" data-datetime="2012-08-08T16:18:14+00:00">August 8, 2012</a></blockquote></div>
	        
				<blockquote class="twitter-tweet"><p>It's really cool to see the bootstrap community step up with projects like this.<a href="http://t.co/YLVWCevr" title="http://www.bootstrapcdn.com/">bootstrapcdn.com</a> &lt;3</p>&mdash; ♒∆✝ (@fat) <a href="https://twitter.com/fat/status/230014001256464384" data-datetime="2012-07-30T18:56:26+00:00">July 30, 2012</a></blockquote>
			 </div>
			<blockquote class="twitter-tweet" data-conversation="none"><p>@<a href="https://twitter.com/andriyko">andriyko</a> Haha, finally? @<a href="https://twitter.com/netdnadeveloper">netdnadeveloper</a> had that shit out in like an hour :).</p>&mdash; Mark Otto (@mdo) <a href="https://twitter.com/mdo/status/263173412984344576">October 30, 2012</a></blockquote>
			
			<blockquote class="twitter-tweet"><p>BootstrapCDN killed it in 2012. Check out their data from the year in review for serving up Bootstrap: <a href="http://t.co/DaOU2uEJ" title="http://blog.netdna.com/opensource/bootstrapcdn/bootstrapcdn-2012-year-in-review/">blog.netdna.com/opensource/boo…</a></p>&mdash; Twitter Bootstrap (@twbootstrap) <a href="https://twitter.com/twbootstrap/status/287063373177307136">January 4, 2013</a></blockquote>
			
			<blockquote class="twitter-tweet"><p>Wow, that was fast. Font Awesome 3.0 is now up on CDN. Thanks, @<a href="https://twitter.com/netdnadeveloper">netdnadeveloper</a>! <a href="http://t.co/d7PzoQH2" title="http://bit.ly/UkT0IS">bit.ly/UkT0IS</a></p>&mdash; Fort Awesome (@fortaweso_me) <a href="https://twitter.com/fortaweso_me/status/286569664862109696">January 2, 2013</a></blockquote>

				<div> <blockquote class="twitter-tweet"><p><a href="http://t.co/GYVUGWg7" title="http://www.bootstrapcdn.com/">bootstrapcdn.com</a> nice to see a CDN like NetDNA take these kind of initiatives</p>&mdash; CDN Planet (@cdnplanet) <a href="https://twitter.com/cdnplanet/status/213008798707744768" data-datetime="2012-06-13T20:43:49+00:00">June 13, 2012</a></blockquote></div>
        	</div>


	<footer class="footer">
			<div class="container">
				<div class="row-fluid">
					<div class="span12">
						<ul class="pull-left">
							<li>Maintained by <a href="http://www.twitter.com/jdorfman" target="_blank">@jdorfman</a>.</li>
							<li>Powered by <a href="http://www.digitalfyre.com" target="_blank">DigitalFyre</a>, <a href="http://www.netdna.com" target="_blank" title="CDN">NetDNA</a>, and <a href="http://www.nginx.org" target="_blank">nginx</a>.</li>
							<li>This free service comes with no warranty.</li>
							<li><a href="terms.html">Terms of Use</a></li>
						</ul>
						<ul class="pull-right">
							<li>Links</li>
							<li><a href="http://twitter.github.com/bootstrap/index.html" target="_blank">Twitter Bootstrap</a></li>
							<li><a href="http://bootswatch.com/" target="_blank">Bootswatch</a></li>
							<li><a href="http://jetstrap.com/" target="_blank">jetstrap</a></li>
							<li><a href="http://bootsnipp.com/" target="_blank">Bootsnipp</a></li>
							<li><a href="http://builtwithbootstrap.com/" target="_blank">Built with Bootstrap</a></li>
							<li><a href="http://www.bootstraphero.com/" target="_blank">Bootstrap Hero</a></li>
							<li><a href="http://stylebootstrap.info/" target="_blank">StyleBootstrap</a></li>
							<li><a href="http://bootswatchr.com/" target="_blank">Bootswatchr</a></li>
							<li><a href="http://www.plugolabs.com/twitter-bootstrap-button-generator/" target="_blank">Bootstrap Button Generator</a></li>
							<li><a href="http://stackoverflow.com/questions/tagged/bootstrap" target="_blank">Bootstrap Q&amp;A on Stackoverflow</a></li>
						</ul>
					</div>
				</div>
			</div>
		</footer>
	</div>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<script src="//platform.twitter.com/widgets.js" charset="utf-8"></script>	
	<script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js"></script>
	<script>$("input:text").focus(function(){$(this).select();$(this).mouseup(function(a){a.preventDefault()})});</script>
	<script>
	// Javascript to enable link to tab
	var hash = document.location.hash;
	var prefix = "tab_";
	if (hash) {
	    $('.nav-tabs a[href='+hash.replace(prefix,"")+']').tab('show');
	} 

	// Change hash for page-reload
	$('.nav-tabs a').on('shown', function (e) {
	    window.location.hash = e.target.hash.replace("#", "#" + prefix);
	});
	</script>
	<script src="http://cdn.webglstats.com/stat.js" defer="defer" async="async"></script>

</body>
</html>
