<?php include "cachebuster.php" ?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>BootstrapCDN: Twitter's Bootstrap hosted on NetDNA's Content Delivery Network</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="With NetDNA's Content Delivery Network, your Bootstrap objects will load faster, a lot faster.">
	<meta name="author" content="Justin Dorfman">
	<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.0.4/css/bootstrap-combined.min.css" rel="stylesheet">		
	<link href="//www.bootstrapcdn.com/css/style.origin.css?v=<?php echo $version ?>" rel="stylesheet">
	<script>
		!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
	</script>

	<!--[if lt IE 9]>
		<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-32253110-1']);
  _gaq.push(['_setDomainName', 'bootstrapcdn.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>

