<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/"><span class="bscdn">Bootstrap CDN</span> <span class="pwr">powered by</span> <span class="netdnabrnd">NetDNA<span></a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><a href="/">Home</a></li>
              <li><a href="https://github.com/netdna/bootstrap-cdn/issues" target="_blank">Issues <i class="icon-white icon-share-alt"></i></a></li>
			  <li class="dropdown" id="menu1">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">
				Reports
				<b class="caret"></b>
				</a>
             			<ul class="dropdown-menu">
				      <li><a href="http://status.bootstrapcdn.com" target="_blank"><i class="icon-ok-sign"></i> Uptime</a></li>
				      <li><a href="stats.html"><i class="icon-tasks"></i> Stats/Charts</a></li>
	    			</ul>
	  </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
