 <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/"><span class="bscdn">Bootstrap CDN</span> <span class="pwr">powered by</span> <span class="netdnabrnd">NetDNA<span></a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><a href="/">Home</a></li>
              <li><a href="https://github.com/jdorfman/bootstrap-cdn/issues" target="_blank">Issues</a></li>
			  <li><a href="http://status.bootstrapcdn.com" target="_blank">Status</a>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

